version: '3.8'
services:
        local-environment:
                image: openjdk:8-alpine
                container_name: local_environment
                ports:
                        - "8080:8080"
                restart: unless-stopped
                
                volumes:
                        - "../target/:/opt/target/"
                
                # CHANGE THIS
                command: ["java","-jar","/opt/target/(project name .jar)"]
