version: '3.8'
services:
        local-environment:
                image: openjdk:8-alpine
                container_name: devs_local_environment
                ports:
                        - "80:8080"
                restart: unless-stopped
                volumes:
                        - "./target/:/opt/target/"

                command: ["java","-jar","/opt/target/booking-0.1.jar"]

                healthcheck:
                        test: wget --no-verbose --tries=1 --spider http://localhost:8080/api/v1.0/bookingFromZero/clients || exit 1
                        interval: 60s
                        retries: 5
                        start_period: 20s
                        timeout: 10s
