# Version '3.8' only will work with a least of docker-compose version 1.29.0
# You should change all the tags that have an 'CHANGE THIS' above.
version: '3.8'
services:
        mysql:
                image: mysql:8.0
                container_name: mysql

                # CHANGE THIS
                environment:
                        MYSQL_ROOT_PASSWORD: your-strong-root-password-here
                        MYSQL_DATABASE: your-database-name-here
                        MYSQL_USER: your-user-name-here
                        MYSQL_PASSWORD: your-user-password-here
                ports:
                        - "3306:3306"

                restart: on-failure

                volumes:
                        - "/opt/mysql-data:/var/lib/mysql"

                healthcheck:
                        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
                        interval: 30s
                        timeout: 10s
                        retries: 5

        pma:
                image: phpmyadmin:5
                container_name: phpmyadmin

                environment:
                        PMA_HOST: mysql
                        PMA_PORT: 3306
                        PMA_ARBITRARY: 1
                ports:
                        - "8081:80"
                
                restart: on-failure
                
                depends_on:
                        mysql:
                                condition: service_healthy

        java:
                image: openjdk:17
                container_name: java
                ports:
                        - "8080:8080"
                restart: on-failure

                # CHANGE THIS 
                volumes:
                        - "path/to/target:/opt/target/"

                # CHANGE THIS
                command: ["java","-jar","/opt/target/your-actual-project.jar"]

                depends_on:
                        mysql:
                                condition: service_healthy
