# Version '3.8' only will work with a least of docker-compose version 1.29.0
# You should change all the tags that have an 'CHANGE THIS' above.
version: '3.8'
services:
        database:
                image: mysql:8.0
                container_name: mysql_db

                # CHANGE THIS
                environment:
                        MYSQL_ROOT_PASSWORD: your-strong-password-here
                ports:
                        - "3306:3306"

                restart: on-failure

                volumes:
                        - "/opt/mysql-db:/var/lib/mysql"

                healthcheck:
                        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
                        interval: 30s
                        timeout: 10s
                        retries: 5
        
        project:
                image: openjdk:8-alpine
                container_name: java_project
                ports:
                        - "8080:8080"
                restart: on-failure

                # CHANGE THIS 
                volumes:
                        - "path/to/project/target:/opt/target/"

                # CHANGE THIS
                command: ["java","-jar","/opt/target/your-actual-project.jar"]

                depends_on:
                        database:
                                condition: service_healthy
