version: '3.8'
services:
        dev_server:
                image: ${DEV_IMAGE}
                env_file:
                        - .env
                container_name: ${CONTAINER}
                ports:
                        - "80:8080"
                restart: unless-stopped
                volumes:
                        - "./jars/${ARTIFACT}:/opt/${ARTIFACT}"
                command: ["java","-jar","/opt/${ARTIFACT}"]

                healthcheck:
                        test: curl --fail http://localhost:8008/ || exit 1
                        interval: 60s
                        retries: 5
                        start_period: 150s
                        timeout: 10s
